//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace StrasInfo.StrasServiceSoap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cts-strasbourg.fr/", ConfigurationName="StrasServiceSoap.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cts-strasbourg.fr/rechercherCodesArretsDepuisLibelle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StrasInfo.StrasServiceSoap.MessageRechercheCodeArret> rechercherCodesArretsDepuisLibelleAsync(string Saisie, int NoPage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cts-strasbourg.fr/rechercheProchainesArriveesWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StrasInfo.StrasServiceSoap.MessageArriveesAppliWeb> rechercheProchainesArriveesWebAsync(string CodeArret, int Mode, string Heure, int NbHoraires);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cts-strasbourg.fr/rechercheFichesHoraires", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StrasInfo.StrasServiceSoap.MessageFichesHoraires> rechercheFichesHorairesAsync(string CodeArret);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cts-strasbourg.fr/infosTrafic", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StrasInfo.StrasServiceSoap.MessageInfosTrafic> infosTraficAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cts-strasbourg.fr/deviations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StrasInfo.StrasServiceSoap.MessageDeviations> deviationsAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cts-strasbourg.fr/")]
    public partial class MessageRechercheCodeArret : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool suiteField;
        
        private Arret[] listeArretField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Suite {
            get {
                return this.suiteField;
            }
            set {
                this.suiteField = value;
                this.RaisePropertyChanged("Suite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Arret[] ListeArret {
            get {
                return this.listeArretField;
            }
            set {
                this.listeArretField = value;
                this.RaisePropertyChanged("ListeArret");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cts-strasbourg.fr/")]
    public partial class Arret : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string libelleField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Libelle {
            get {
                return this.libelleField;
            }
            set {
                this.libelleField = value;
                this.RaisePropertyChanged("Libelle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cts-strasbourg.fr/")]
    public partial class Deviation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string titreField;
        
        private string descriptionField;
        
        private System.DateTime debutField;
        
        private System.DateTime finField;
        
        private string categorieField;
        
        private bool exergueField;
        
        private int positionField;
        
        private string[] lignesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Titre {
            get {
                return this.titreField;
            }
            set {
                this.titreField = value;
                this.RaisePropertyChanged("Titre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime Debut {
            get {
                return this.debutField;
            }
            set {
                this.debutField = value;
                this.RaisePropertyChanged("Debut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime Fin {
            get {
                return this.finField;
            }
            set {
                this.finField = value;
                this.RaisePropertyChanged("Fin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Categorie {
            get {
                return this.categorieField;
            }
            set {
                this.categorieField = value;
                this.RaisePropertyChanged("Categorie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool Exergue {
            get {
                return this.exergueField;
            }
            set {
                this.exergueField = value;
                this.RaisePropertyChanged("Exergue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("Position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public string[] Lignes {
            get {
                return this.lignesField;
            }
            set {
                this.lignesField = value;
                this.RaisePropertyChanged("Lignes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cts-strasbourg.fr/")]
    public partial class MessageDeviations : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Deviation[] deviationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Deviation[] Deviations {
            get {
                return this.deviationsField;
            }
            set {
                this.deviationsField = value;
                this.RaisePropertyChanged("Deviations");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cts-strasbourg.fr/")]
    public partial class InfoTrafic : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string titreField;
        
        private string descriptionField;
        
        private System.DateTime debutField;
        
        private System.DateTime finField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Titre {
            get {
                return this.titreField;
            }
            set {
                this.titreField = value;
                this.RaisePropertyChanged("Titre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime Debut {
            get {
                return this.debutField;
            }
            set {
                this.debutField = value;
                this.RaisePropertyChanged("Debut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime Fin {
            get {
                return this.finField;
            }
            set {
                this.finField = value;
                this.RaisePropertyChanged("Fin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cts-strasbourg.fr/")]
    public partial class MessageInfosTrafic : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InfoTrafic[] infosTraficField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public InfoTrafic[] InfosTrafic {
            get {
                return this.infosTraficField;
            }
            set {
                this.infosTraficField = value;
                this.RaisePropertyChanged("InfosTrafic");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cts-strasbourg.fr/")]
    public partial class FicheHoraire : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string libelleDestinationField;
        
        private string urlField;
        
        private System.DateTime debutValiditeField;
        
        private System.DateTime finValiditeField;
        
        private int typePeriodeField;
        
        private string libellePeriodeField;
        
        private string codeArretField;
        
        private string ligneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LibelleDestination {
            get {
                return this.libelleDestinationField;
            }
            set {
                this.libelleDestinationField = value;
                this.RaisePropertyChanged("LibelleDestination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("Url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime DebutValidite {
            get {
                return this.debutValiditeField;
            }
            set {
                this.debutValiditeField = value;
                this.RaisePropertyChanged("DebutValidite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime FinValidite {
            get {
                return this.finValiditeField;
            }
            set {
                this.finValiditeField = value;
                this.RaisePropertyChanged("FinValidite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int TypePeriode {
            get {
                return this.typePeriodeField;
            }
            set {
                this.typePeriodeField = value;
                this.RaisePropertyChanged("TypePeriode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LibellePeriode {
            get {
                return this.libellePeriodeField;
            }
            set {
                this.libellePeriodeField = value;
                this.RaisePropertyChanged("LibellePeriode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CodeArret {
            get {
                return this.codeArretField;
            }
            set {
                this.codeArretField = value;
                this.RaisePropertyChanged("CodeArret");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Ligne {
            get {
                return this.ligneField;
            }
            set {
                this.ligneField = value;
                this.RaisePropertyChanged("Ligne");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cts-strasbourg.fr/")]
    public partial class MessageFichesHoraires : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FicheHoraire[] fichesHorairesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public FicheHoraire[] FichesHoraires {
            get {
                return this.fichesHorairesField;
            }
            set {
                this.fichesHorairesField = value;
                this.RaisePropertyChanged("FichesHoraires");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cts-strasbourg.fr/")]
    public partial class Arrivee : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string modeField;
        
        private string destinationField;
        
        private string horaireField;
        
        private bool estApresMinuitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
                this.RaisePropertyChanged("Mode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("Destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Horaire {
            get {
                return this.horaireField;
            }
            set {
                this.horaireField = value;
                this.RaisePropertyChanged("Horaire");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool EstApresMinuit {
            get {
                return this.estApresMinuitField;
            }
            set {
                this.estApresMinuitField = value;
                this.RaisePropertyChanged("EstApresMinuit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cts-strasbourg.fr/")]
    public partial class MessageArriveesAppliWeb : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Arrivee[] listeArriveeField;
        
        private string libelleArretField;
        
        private string heureDemandeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Arrivee[] ListeArrivee {
            get {
                return this.listeArriveeField;
            }
            set {
                this.listeArriveeField = value;
                this.RaisePropertyChanged("ListeArrivee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LibelleArret {
            get {
                return this.libelleArretField;
            }
            set {
                this.libelleArretField = value;
                this.RaisePropertyChanged("LibelleArret");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string HeureDemande {
            get {
                return this.heureDemandeField;
            }
            set {
                this.heureDemandeField = value;
                this.RaisePropertyChanged("HeureDemande");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cts-strasbourg.fr/")]
    public partial class CredentialHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string mDPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MDP {
            get {
                return this.mDPField;
            }
            set {
                this.mDPField = value;
                this.RaisePropertyChanged("MDP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : StrasInfo.StrasServiceSoap.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<StrasInfo.StrasServiceSoap.ServiceSoap>, StrasInfo.StrasServiceSoap.ServiceSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoapClient() : 
                base(ServiceSoapClient.GetDefaultBinding(), ServiceSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.ServiceSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<StrasInfo.StrasServiceSoap.MessageRechercheCodeArret> rechercherCodesArretsDepuisLibelleAsync(string Saisie, int NoPage) {
            return base.Channel.rechercherCodesArretsDepuisLibelleAsync(Saisie, NoPage);
        }
        
        public System.Threading.Tasks.Task<StrasInfo.StrasServiceSoap.MessageArriveesAppliWeb> rechercheProchainesArriveesWebAsync(string CodeArret, int Mode, string Heure, int NbHoraires) {
            return base.Channel.rechercheProchainesArriveesWebAsync(CodeArret, Mode, Heure, NbHoraires);
        }
        
        public System.Threading.Tasks.Task<StrasInfo.StrasServiceSoap.MessageFichesHoraires> rechercheFichesHorairesAsync(string CodeArret) {
            return base.Channel.rechercheFichesHorairesAsync(CodeArret);
        }
        
        public System.Threading.Tasks.Task<StrasInfo.StrasServiceSoap.MessageInfosTrafic> infosTraficAsync() {
            return base.Channel.infosTraficAsync();
        }
        
        public System.Threading.Tasks.Task<StrasInfo.StrasServiceSoap.MessageDeviations> deviationsAsync() {
            return base.Channel.deviationsAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap)) {
                return new System.ServiceModel.EndpointAddress("http://opendata.cts-strasbourg.fr/webservice_v4/Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return ServiceSoapClient.GetBindingForEndpoint(EndpointConfiguration.ServiceSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return ServiceSoapClient.GetEndpointAddress(EndpointConfiguration.ServiceSoap);
        }
        
        public enum EndpointConfiguration {
            
            ServiceSoap,
        }
    }
}
